### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Cfgaar** [tsarvs/MusighScraper#1]
Traceback (most recent call last):
  File "ScraperDriver.py", line 165, in <module>
    main()
  File "ScraperDriver.py", line 161, in main
    scrapeMusic()
  File "ScraperDriver.py", line 122, in scrapeMusic
    blogpost = getLatestPost()
  File "ScraperDriver.py", line 16, in getLatestPost
    latestPostURL = getSoup(homePage).find("div", id="content").find_all("div", class_="post-title")[0].find("a")['href']
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by tsarvs** [comment]
Issue should be resolved now. Originally, the webserver that musigh is on was rejecting http requests, so I used a python library that emulated a browser instead of calling the pages directly from the python code.
